# Numpy(Numerical Python)

Numpy의 주요 기능   numeric : 숫자
- 정의 :  빠르고 효율적인 벡터(값 하나라고 생각해라) 산술연산을 제공하는 다차원(n-dimension)배열 제공(ndarray 클래스)
- 생성
    - import numpy as np
    - arr = __np.array(iterableOb, dtype=np.int32)__  *단 동일 자료형*
    - 동일 숫자 : np.full((행,열), 채울 숫자 data ), np.zeros((행,열)), np.ones((행,열))
    - 일정범위의 숫자 : np.arange(from,to,step) 실수값 가능  cf)range : 정수
    - 0~1실수랜덤 : np.random.rand(shape) *연산하여 범위 변경 가능
    - 정수 랜덤 : np.random.randint(from, to, size=(행,열))
- 속성
    - .shape : 몇행 몇열 즉 배열의 크기 확인.
    - .size : 배열 요소 개수 확인
    - .ndim : 배열의 차원 확인
    - .dtype : 배열의 타입확인. int32, int64, float32..
- 함수
    - 1차원을 2차원으로 : arr.reshape(행,열)
    - 타입변경 : arr = arr.astype('바꿀타입')
    - np.sum(arr), np.sqrt(arr), np.mean(arr), np.abs(arr), np.unique(arr)
- 연산 : /3행5열/과 /단일숫자, 1행5열, 3행1열, 3행5열/의 ndarray는 서로 연산가능 : 자동으로 행열 복사 후 같은 인덱스끼리 사칙연산
- 인덱싱과 슬라이싱 : 값을 할당함으로써 일괄 수정도 가능 ex) arr[ : ]=4
    - [행 , 열]제공
    - [[행] , [열]] 다중인덱싱 but결과는 1차원 배열
    - [[행:행], [열:열]] : 다중슬라이싱 2차원 리턴
    - [조건, 열] : boolean과 동시 사용 가능
- 외부 자료(txt) 활용
    - data = __np.loadtxt('파일명.확장자',delimiter=',')__ //de-limit-er , dtype=''같은 거 추가 가능
    - 내보내기 : np.savetxt('파일명.확장자')

In [2]:
import numpy as np

numpy.ndarray 클래스
- 동일한 자료형을 가지는 값들이 배열 형태로 존재함
- n차원 행태로 구성 가능
- 각 값들은 양의 정수로 색인(index)이 부여되어 있다. 0.1,2,3,...
- numpy에서 차원(dimension)을 rank, axis라고 부르기도 한다.
- ndarray를 줄여서 array로 표현한다.

- 1차원 ndarray 생성하기
    - arr1 = np.array(iterable)

In [3]:
list1=[1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [4]:
arr1 = np.array(list1)   # = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

- 2,3차원 ndarray 생성하기

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr3 = np.array([[[1,2,3,4],[3,4,5,6],[5,6,7,8]],[[1,2,3,4],[3,4,5,6],[5,6,7,8]]])
arr3

array([[[1, 2, 3, 4],
        [3, 4, 5, 6],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [3, 4, 5, 6],
        [5, 6, 7, 8]]])

- ndarray 속성값  
    - .shape : 배열의 크기 확인. (행개수, 열개수) 알려줌
    - .size : 배열 요소 개수 확인
    - .ndim : 배열의 차원 확인
    - .dtype : 배열의 타입확인

In [53]:
print(arr1.shape)  #(열,)
print(arr2.shape)  #(행,열)
print(arr3.shape)  #(높이,행,열)
print(len(arr3))   #가장 바깥쪽 차원 요소의 개수(axis=0 고정)
print(len(arr2))
print(len(arr1))

(5,)
(2, 3)
(2, 3, 4)
2
2
5


In [8]:
print(arr1.size)  # shape 값들의 곱
print(arr2.size)
print(arr3.size)

5
6
24


In [9]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [10]:
print(arr1.dtype)  # 뒤에 나온 숫자는 32bit(=4byte-> int)를 말함.

int32


In [11]:
print("배열의 크기 :",arr3.shape)
print("배열의 차원 :",arr3.ndim)
print("배열의 개수 :",arr3.size)

배열의 크기 : (2, 3, 4)
배열의 차원 : 3
배열의 개수 : 24


### np함수1

- 특정 숫자데이터로 ndarray 생성 및 초기화해주는 np함수
    - 0 : np.zeros((shape))
    - 1 : np.ones((shape))
    - 그외숫자 : np.full((shape), 그외숫자)
    - __수열 : np.arange(from, to, step) - step기본값은 1(실수값도 가능)__
    - 실수랜덤값(0~1) : np.random.rand(shape)  - 이 자체에 +,* 등 연산추가하여 값 범위 변경 가능, 괄호개수 유의
    - __정수랜덤값 : np.random.randint(from,to, size=(shape)) - 역시 연산 가능__
- 1차원으로 만든 ndarray를 2차원으로 바꾸기
    - arr=np.arange(50).reshape(5,10)  - 5,10 = shape

In [12]:
#0 (shift + tap 눌러보면 기본형 float으로 되어있다.)
arr_zero = np.zeros((2,2))  #2차원 배열 -> tuple형태()로 행과 열의 개수 지정하기
arr_zero

array([[0., 0.],
       [0., 0.]])

In [13]:
#1
arr_one = np.ones((3,4))
arr_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
#내가 원하는 값으로
arr_full = np.full((2,2),4)
arr_full

array([[4, 4],
       [4, 4]])

In [15]:
#1~50까지의 숫자데이터를 가지고 있는 1차원 배열 arr4 생성
#np.array() -> numpy 배열 생성하는 기능의 매개변수로 들어갈 수 있는 자료구조는?

In [16]:
i=1
list_tem=[]
for i in range(1,51):
    list_tem.append(i)        

#  while i<51 :
#      list_tem.append(i)
#      i += 1
arr4 = np.array(list_tem)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [56]:
arr5 = np.arange(1,51,1) #arange(시작값, 끝값+1, 증감값)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [58]:
arr6 = np.arange(1, 2, 0.05)
arr6

array([1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ,
       1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95])

In [59]:
#0~1 사이의 랜덤값 집어넣으면서 배열 생성하기
arr_ran = np.random.rand(2,3)+1   #random.rand(행,열)
arr_ran

array([[1.35933124, 1.60327366, 1.26004801],
       [1.3267722 , 1.67643241, 1.57002702]])

In [19]:
#정수 랜덤값 짛어넣으면서 배열 생성하기
arr_int = np.random.randint(2,10, size = (2,3))
arr_int

array([[7, 9, 8],
       [5, 8, 3]])

- 배열의 타입 바꾸기
    - 생성시 바꾸기 : 배열명=np.array([ , , ], dtype=np.__int64__)
    - 생성된 ndarray 바꾸기 : 배열명 = 기존배열명.astype('int64') (배열명과 기존배열명은 같아도 됨)

In [61]:
#배열 타입을 생성과 동시에 바꾸기 (int32, int64 상관없음)
arr_type = np.array([1.1,2.2],dtype=np.int32)
arr_type

array([1, 2])

In [21]:
#생성된 배열의 타입을 바꿔보기
arr_type = arr_type.astype('float64')
arr_type

array([1., 2.])

In [22]:
arr_type = arr_type.astype('int64')
arr_type

array([1, 2], dtype=int64)

Array 연산 : broadcasting 또는 repeat가 자동으로 되나봐
- shape이 같은 배열과 배열의 연산 가능(같은 인덱스끼리 사칙연산)
- shape이 다를 경우, 한 배열이 한 행 또는 한 열만을 가지고 있고, 각각 열의 개수가 같거나 행의 개수가 같으면 연산 가능(부족한 행이나 열은 알아서 복사) ex)[3행5열]에 [1행 5열] 또는 [3행 1열]은 연산 가능
- 배열에 배열이 아닌 특정 값을 연산하는 것은 상관없음 ex)arr+1=모든 요소에 +1

In [23]:
arr6 = np.array([1,2,3])
arr6

array([1, 2, 3])

In [24]:
print(arr6+arr6)
print(arr6*arr6)
print(arr6-arr6)
print(arr6/arr6)

[2 4 6]
[1 4 9]
[0 0 0]
[1. 1. 1.]


In [25]:
arr8 = np.array([[1,2,3],[3,4,5],[7,8,9]])
arr8+arr6

array([[ 2,  4,  6],
       [ 4,  6,  8],
       [ 8, 10, 12]])

### ndarray 인덱싱과 슬라이싱  [   ,  ] 
일반 인덱싱,슬라이싱과의 차이

- [행][행][행이하나일때 열] 이 구조는 동일
-------
- [행,열]검색 제공 : 쉼표는 행과 열을 구분하는 기호
- [[ , , ], [ , , ]] 인덱스 번호를 배열형태로 입력 가능 -> 다중 인덱싱가능. 슬라이싱과 달리 여러행에서 값을 가져오더라도 1차원으로 반환함
    - 안쪽 괄호 안의 쉼표는 배열에서 값을 구분하는 기호
    - 즉 [[행1,행2],[열1,열2]..], [(행1,행2),(열1,열2)..] 이런 의미. 이때 [행1,열1],[행2,열2] 두 개의 값만 반환. 따라서 행과 열의 개수 맞아야
    - 그래서 다중 슬라이싱(?)(ex[[1,2],[2,3,7,8]]또는 [[1:3],[2:4,7:9]])는 불가. 행이든 열이든 하나를 고정해서 하는 것이 최선(list[[1,[2,3,7,8]], list[[2,[2,3,7,8]]) __판다스는 아마 가능__
    
    

- 슬라이싱 후 일괄 수정 가능 : arr[0:2,1:4]=4  
- (공통점)행은 생략불가 [1, ]=[1, : ]=[1] but [ ,1]은 에러

In [26]:
#[행index,열index] 기존처럼 [행index][열index] 해도 됨
#ndarrage가 아니면 [행,열] 불가함!!
print(arr8[:,1])
print(arr8[1])

[2 4 8]
[3 4 5]


In [27]:
arr9=np.arange(1,11)
arr9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
#슬라이싱 한 구간을 특정 값으로 일괄 수정 가능
arr9[2:6] = 4
arr9

array([ 1,  2,  4,  4,  4,  4,  7,  8,  9, 10])

In [29]:
arr10=np.arange(50).reshape(5,10)
arr10

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [30]:
arr10[0:3,3:6][0:2]

array([[ 3,  4,  5],
       [13, 14, 15]])

In [31]:
print(arr10[2,[1,2,3,6,7,8]],arr10[3,[1,2,3,6,7,8]])
print(arr10[[2,2,2,2,2,2,3,3,3,3,3,3],[1,2,3,6,7,8,1,2,3,6,7,8]])

[21 22 23 26 27 28] [31 32 33 36 37 38]
[21 22 23 26 27 28 31 32 33 36 37 38]


In [32]:
arr11=np.array(arr10[2:4,1:9])
arr11

array([[21, 22, 23, 24, 25, 26, 27, 28],
       [31, 32, 33, 34, 35, 36, 37, 38]])

In [33]:
arr10[0:2,3:5]

array([[ 3,  4],
       [13, 14]])

In [34]:
#2차원 슬라이싱 1행 3열~6열까지
arr10[1,3:7]

array([13, 14, 15, 16])

In [35]:
#전체행의 0열만
arr10[:,1]

array([ 1, 11, 21, 31, 41])

외부파일 분석하기  
- 외부파일 업로드 : 가급적 작업중인 폴더에 드래그앤드랍->업로드  
- 파일 불러오기 : data = np.loadtxt('파일명.확장자',delimiter=',') - '정확한 파일명과 확장자',delimiter='구분기호'
- 파일 내보내기 : np.savetxt()

In [63]:
data=np.loadtxt('height_weight.txt',delimiter=',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [64]:
print(data.shape)
print(data.dtype)

(2, 10)
float64


In [68]:
bmi=data[1]/(data[0]/100)**2 #=(data[0,:]/100)*(data[0,:]/100) #data[1,:]=data[1]
bmi.astype('int32')


array([21, 27, 25, 24, 16, 20, 23, 21, 23, 25])

In [39]:
for i in bmi :
    print(round(i,3))

21.372
27.07
25.861
24.207
16.035
20.145
23.144
21.697
23.62
25.592


### Boolean 색인 : 배열[조건식]
- 연산 및 비교연산 등이 가능하기 때문에 작동하는 것. 
- 인덱싱할 값에 조건식을 넣어주는 것에 불과 -> 숫자 인덱싱과 함께 사용 가능 [조건,숫자]
- 배열 = 배열[boolean배열]

In [40]:
name = np.array(["운비","수민","병만","진웅"])
name

array(['운비', '수민', '병만', '진웅'], dtype='<U2')

In [41]:
bol = np.array([False,True,False,True])
bol

array([False,  True, False,  True])

In [42]:
name[bol]

array(['수민', '진웅'], dtype='<U2')

In [43]:
score = np.array([[60,60],[70,70],[80,80],[90,90]])
score

array([[60, 60],
       [70, 70],
       [80, 80],
       [90, 90]])

In [44]:
#내가 찾고자 하는 이름이 있는지 색인!
name == "운비"

array([ True, False, False, False])

In [45]:
#내가 찾고자 하는 이름의 점수를 색인하기
score[name == '운비']

array([[60, 60]])

In [46]:
score[name=='다연']  #없는 값 넣으면 빈 배열 반환

array([], shape=(0, 2), dtype=int32)

### np함수2  
함수 문법같은 거 종종 바뀌는 편.. 

- np.sum(arr) -> arr.sum() 간편한 형식 지원해줌
- np.mean(arr) -> arr.mean() 간편한 형식 지원해줌
- np.sqrt(arr)
- np.abs(arr)
- np.unique(arr) : 배열 내의 중복값 제거

In [47]:
#sum() : 합계를 구할 수 있는 함수
#arr 1~10을 사용하여 크기가 2행 5열인 array만들기
arr141=np.random.randint(1,11, size=(2,5))
arr141

array([[10,  8,  6,  2,  9],
       [ 6, 10, 10,  2,  9]])

In [48]:
#형식1 : 변수명.sum() ---- 더 간단해서 많이 쓰임
arr141.sum()

72

In [49]:
#형식2 : 사용하고자 하는 함수(매개변수는 변수명)
np.sum(arr141)

72

In [50]:
# 평균 구하는 함수 : mean() -> 전체 요솟값에 대해 평균을 구해주는 함수
print(arr141.mean())
print(np.mean(arr141))

7.2
7.2


In [51]:
# 제곱근 구하는 함수 : np.sqrt(arr). 
np.sqrt(arr141)

array([[3.16227766, 2.82842712, 2.44948974, 1.41421356, 3.        ],
       [2.44948974, 3.16227766, 3.16227766, 1.41421356, 3.        ]])

In [52]:
# 절대값 구하는 함수 : np.abs(arr)
arr142=np.array([-3,-2,-1])
np.abs(arr142)


array([3, 2, 1])